[project]
name = "qliq-ai-assistant"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "boto3-stubs==1.39.12",
    "langchain-community>=0.3.27",
    "pandas-stubs==2.3.0.250703",
]
